services:
  web:
    build: .
    command: python /opt/wcms/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./wcms:/opt/wcms
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - 'DJANGO_SECRET_KEY=django-insecure-9e-c64k9x5vjw0o^*w83kkg9#lset2p8i9q!$$bfp2+pei%4h0#'
      - "DJANGO_DEBUG=True"
      - "DJANGO_SECURE_SSL_REDIRECT=False"  
      - "DJANGO_SECURE_HSTS_SECONDS=0"  
      - "DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS=False"  
      - "DJANGO_SECURE_HSTS_PRELOAD=False"  
      - "DJANGO_SESSION_COOKIE_SECURE=False"  
      - "DJANGO_CSRF_COOKIE_SECURE=False"  
    env_file:
      - .env.local
      
  db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.local

volumes:
  postgres_data: