# Generated by Django 5.2.3 on 2025-06-26 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogpage_authors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='authors',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
