# Generated by Django 5.2.3 on 2025-06-30 00:28

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('text_image', 3)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link']}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('image_left', 'Image Left, Text Right'), ('image_right', 'Text Left, Image Right')]}), 3: ('wagtail.blocks.StructBlock', [[('text', 0), ('image', 1), ('layout', 2)]], {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='flexiblecontentpage',
            name='body',
            field=wagtail.fields.StreamField([('text_block', 0), ('image_block', 1), ('image_text_block', 4)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['h1', 'h2', 'h3', 'bold', 'italic', 'link']}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 3: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 4: ('wagtail.blocks.StructBlock', [[('image', 2), ('text', 3)]], {})}),
        ),
    ]
