# Generated by Django 5.2.3 on 2025-07-01 11:28

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_flexiblecontentpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockpage',
            name='body',
            field=wagtail.fields.StreamField([('text_image', 4)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link']}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('image_left', 'Image Left, Text Right'), ('image_right', 'Text Left, Image Right')]}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left-top', 'Left Top'), ('left-middle', 'Left Middle'), ('left-bottom', 'Left Bottom'), ('center-top', 'Center Top'), ('center-middle', 'Center Middle'), ('center-bottom', 'Center Bottom'), ('right-top', 'Right Top'), ('right-middle', 'Right Middle'), ('right-bottom', 'Right Bottom')], 'help_text': 'Position the text relative to the image', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('text', 0), ('image', 1), ('layout', 2), ('text_alignment', 3)]], {})}),
        ),
    ]
