# Generated by Django 5.2.3 on 2025-07-01 11:32

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_blockpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexiblecontentpage',
            name='body',
            field=wagtail.fields.StreamField([('text_block', 0), ('image_block', 1), ('image_text_block', 5), ('studio_activities', 13)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['h1', 'h2', 'h3', 'bold', 'italic', 'link']}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link']}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('image_left', 'Image Left, Text Right'), ('image_right', 'Text Left, Image Right')]}), 4: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left-top', 'Left Top'), ('left-middle', 'Left Middle'), ('left-bottom', 'Left Bottom'), ('center-top', 'Center Top'), ('center-middle', 'Center Middle'), ('center-bottom', 'Center Bottom'), ('right-top', 'Right Top'), ('right-middle', 'Right Middle'), ('right-bottom', 'Right Bottom')], 'help_text': 'Position the text relative to the image', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('text', 2), ('image', 1), ('layout', 3), ('text_alignment', 4)]], {}), 6: ('wagtail.blocks.CharBlock', (), {'default': 'Mida saab akvarellistuudios teha?', 'required': True}), 7: ('wagtail.blocks.CharBlock', (), {'required': True}), 8: ('wagtail.blocks.TextBlock', (), {'required': True}), 9: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 10: ('wagtail.blocks.PageChooserBlock', (), {'required': True}), 11: ('wagtail.blocks.StructBlock', [[('title', 7), ('description', 8), ('image', 9), ('link', 10)]], {}), 12: ('wagtail.blocks.ListBlock', (11,), {}), 13: ('wagtail.blocks.StructBlock', [[('heading', 6), ('cards', 12)]], {})}),
        ),
    ]
