# Generated by Django 5.2.3 on 2025-07-01 14:08

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_flexiblecontentpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexiblecontentpage',
            name='body',
            field=wagtail.fields.StreamField([('text_block', 0), ('image_block', 1), ('image_text_block', 4), ('studio_activities', 12)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['h1', 'h2', 'h3', 'bold', 'italic', 'link', 'left', 'center', 'right', 'justify']}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('image_left', 'Image Left, Text Right'), ('image_right', 'Text Left, Image Right')]}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left-top', 'Left Top'), ('left-middle', 'Left Middle'), ('left-bottom', 'Left Bottom'), ('center-top', 'Center Top'), ('center-middle', 'Center Middle'), ('center-bottom', 'Center Bottom'), ('right-top', 'Right Top'), ('right-middle', 'Right Middle'), ('right-bottom', 'Right Bottom')], 'help_text': 'Position the text relative to the image', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('text', 0), ('image', 1), ('layout', 2), ('text_alignment', 3)]], {}), 5: ('wagtail.blocks.CharBlock', (), {'default': 'Mida saab akvarellistuudios teha?', 'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'required': False}), 7: ('wagtail.blocks.TextBlock', (), {'required': False}), 8: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 9: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 10: ('wagtail.blocks.StructBlock', [[('title', 6), ('description', 7), ('image', 8), ('link', 9)]], {}), 11: ('wagtail.blocks.ListBlock', (10,), {}), 12: ('wagtail.blocks.StructBlock', [[('heading', 5), ('cards', 11)]], {})}),
        ),
    ]
